### ISSUE TITLE
Move to Storeon org

### ISSUE THREAD

**Issue by distolma** [storeon/vue#1]
Hi @ai, please add me to the contributors to provide permission for configuration

**Comment by ai** [comment]
Done. I also renamed it to `storeon/vue` to keep the name convention.

Ping me after `@storeon/vue` npm package release, I will change your rights in npm too.

**Comment by distolma** [comment]
The package is released https://www.npmjs.com/package/@storeon/vue

**Comment by ai** [comment]
npm access was updated
