### ISSUE TITLE
Add Comparison with Vuex

### ISSUE THREAD

**Issue by ai** [storeon/vue#2]
We need to compare Storeon to Vuex in the docs since most of the Vue.js users will want to know it.

I see:
1. The size
2. Performance (do we subscribe to changes of specific store’s keys?)

**Comment by ai** [comment]
We also need to clarify what is Storeon in your docs, so people will not need extra click.

At least that it is state manager.

**Comment by distolma** [comment]
Fixed with https://github.com/storeon/vue/commit/688205db08ed8b9309b6dc5cb68bb3acbb1b3bfd commit
